version: '2'
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks: 
      - kafka_network
  kafka:
    # image: niks123123/kafka
    build: .
    container_name: kafka
    networks: 
      - kafka_network
    ports:
      - 29092:29092
      - 29093:29093
    environment:
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,EXTERNAL_DIFFERENT_HOST://:29093,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092,EXTERNAL_DIFFERENT_HOST://1.237.200.53:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT,EXTERNAL_DIFFERENT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CREATE_TOPICS: "test_topic:1:1,seven_bread:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    # environment:
    #   DOCKER_API_VERSION: 1.22
    #   # KAFKA_ADVERTISED_PORT: 9092
    #   # KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    #   # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.29.104:9092
    #   # KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    #   # KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    #   # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
    #   # KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://192.168.29.104:9094
    #   # KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://192.168.29.104:9094
    #   # KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    #   KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
    #   KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
    #   KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
    #   KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    #   KAFKA_CREATE_TOPICS: "test_topic:1:1,seven_bread:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
networks:
  kafka_network:
    name: kafka_docker_example_net
