version: "3.7"

services:

  db:
    image: mariadb
    ports:
        - 3307:3306
    restart: always
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: P!ssw0rd
      MYSQL_DATABASE: clouddb
      MYSQL_USER: cloud
      MYSQK_PASSWORD: P!ssw0rd
    volumes:
        - /Users/james/myprojects/cloud-projects/cloud-infra/mariadb/data:/var/lib/mysql
        - /Users/james/myprojects/cloud-projects/cloud-infra/mariadb/my.cnf:/etc/mysql/my.cnf
        - /Users/james/myprojects/cloud-projects/cloud-infra/mariadb/data/init.sql:/data/application/init.sql